### PR TITLE
Per cust coupon

### PR DESCRIPTION
**Pull request by bhsmither**
Adds database columns to flag a coupon as a "uses per customer" limit, and to record what coupon was used in the order.

Adds code to check for prior uses of this coupon by this customer.

Adds language explaining why this coupon is not accepted.

### CODE REVIEW

**Comment by abrookbanks** [comment]
Thanks for this Brian. I'll see about adding it to 6.2.0.

**Comment by briansandall** [comment]
@bhsmither Are the changes to .gitignore required for this PR, or just included accidentally? I don't see any need to update the current .gitignore file.

**Comment by bhsmither** [comment]
I do not know how to exclude that file in the PR.

I added it to my local copy (cloned from my Github fork of CC6), but it propagated all the way back up.

**Comment by briansandall** [comment]
For PRs, the usual work flow is to start with a clean version of the forked project, i.e. without any customizations.

From there, make a new branch with only the changes needed to resolve whatever issue or feature it is you are working on, and submit that as the PR.

In this case, what you can do is:

- Checkout the latest CubeCart master branch and make a temporary branch off of it

- Cherry-pick the one commit you need from this current PR to the temporary branch

- Force delete (or rename) the old branch

- Rename the temporary branch to the same name as the old branch

- Force push the new version; this will update the PR with the cleaned veersion

**Comment by briansandall** [comment]
That will also give you a chance to resolve the conflict in 6.1.6.sql.

**Comment by abrookbanks** [comment]
That would be a help but I can work with this anyway.

**Comment by briansandall** [comment]
Of course - I'm just very particular about commit history and was explaining how to keep it clean, if desired. :)

**Comment by abrookbanks** [comment]
I'm going to create a branch for 6.2.0 shortly and I will then merge this and test it out. Thanks for your patience. It will be nice to have a better development structure like this soon....

**Pull request closed without merging**
