### PR TITLE
Issue #976 - new products 'featured' by default

### PR DESCRIPTION
**Pull request by briansandall**
As discussed ;)

### CODE REVIEW

**Comment by abrookbanks** [comment]
Looks good. GREAT!! :)

**Comment by abrookbanks** [comment]
Almost. I had to change one extra line of code for it to be checked by default.

**Comment by briansandall** [comment]
Which line? It was checked for me when I went to create a new product.

**Comment by abrookbanks** [comment]
> Which line? It was checked for me when I went to create a new product.

No line I was wrong. It was perfect. Ignore that comment. My day is heading towards and end and I'm getting a bit code blind.

**Comment by briansandall** [comment]
Totally understand - it all kind of blurs together when no amount of coffee will keep the eyelids open any longer. Get some rest ;)

**Pull request merged**
